name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build
    - name: Install local registry
      run: |
        /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install fair-cli from pip
      run: pip install fair-cli
    - name: run javaSimpleModel with fair cli
      run: |
        ~/.local/bin/fair init --ci
        ~/.local/bin/fair pull src/main/resources/seirs-config.yaml
        ~/.local/bin/fair run  src/main/resources/seirs-config.yaml
        
